/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cloud.tags.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CustomerImages service. Represents a row in the &quot;designers_customer_images&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cloud.tags.model.impl.CustomerImagesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cloud.tags.model.impl.CustomerImagesImpl}.
 * </p>
 *
 * @author Mohammed Zaheer
 * @see CustomerImages
 * @see com.cloud.tags.model.impl.CustomerImagesImpl
 * @see com.cloud.tags.model.impl.CustomerImagesModelImpl
 * @generated
 */
public interface CustomerImagesModel extends BaseModel<CustomerImages> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer images model instance should use the {@link CustomerImages} interface instead.
	 */

	/**
	 * Returns the primary key of this customer images.
	 *
	 * @return the primary key of this customer images
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this customer images.
	 *
	 * @param primaryKey the primary key of this customer images
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the customer image ID of this customer images.
	 *
	 * @return the customer image ID of this customer images
	 */
	public long getCustomerImageId();

	/**
	 * Sets the customer image ID of this customer images.
	 *
	 * @param customerImageId the customer image ID of this customer images
	 */
	public void setCustomerImageId(long customerImageId);

	/**
	 * Returns the designer s k u of this customer images.
	 *
	 * @return the designer s k u of this customer images
	 */
	@AutoEscape
	public String getDesignerSKU();

	/**
	 * Sets the designer s k u of this customer images.
	 *
	 * @param designerSKU the designer s k u of this customer images
	 */
	public void setDesignerSKU(String designerSKU);

	/**
	 * Returns the designer cus image of this customer images.
	 *
	 * @return the designer cus image of this customer images
	 */
	@AutoEscape
	public String getDesignerCusImage();

	/**
	 * Sets the designer cus image of this customer images.
	 *
	 * @param designerCusImage the designer cus image of this customer images
	 */
	public void setDesignerCusImage(String designerCusImage);

	/**
	 * Returns the customer image of this customer images.
	 *
	 * @return the customer image of this customer images
	 */
	@AutoEscape
	public String getCustomerImage();

	/**
	 * Sets the customer image of this customer images.
	 *
	 * @param customerImage the customer image of this customer images
	 */
	public void setCustomerImage(String customerImage);

	/**
	 * Returns the customer name of this customer images.
	 *
	 * @return the customer name of this customer images
	 */
	@AutoEscape
	public String getCustomerName();

	/**
	 * Sets the customer name of this customer images.
	 *
	 * @param customerName the customer name of this customer images
	 */
	public void setCustomerName(String customerName);

	/**
	 * Returns the customer address of this customer images.
	 *
	 * @return the customer address of this customer images
	 */
	@AutoEscape
	public String getCustomerAddress();

	/**
	 * Sets the customer address of this customer images.
	 *
	 * @param customerAddress the customer address of this customer images
	 */
	public void setCustomerAddress(String customerAddress);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CustomerImages customerImages);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CustomerImages> toCacheModel();

	@Override
	public CustomerImages toEscapedModel();

	@Override
	public CustomerImages toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}