/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cloud.tags.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DesignersBarcode service. Represents a row in the &quot;designer_barcodes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cloud.tags.model.impl.DesignersBarcodeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cloud.tags.model.impl.DesignersBarcodeImpl}.
 * </p>
 *
 * @author Mohammed Zaheer
 * @see DesignersBarcode
 * @see com.cloud.tags.model.impl.DesignersBarcodeImpl
 * @see com.cloud.tags.model.impl.DesignersBarcodeModelImpl
 * @generated
 */
public interface DesignersBarcodeModel extends BaseModel<DesignersBarcode> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a designers barcode model instance should use the {@link DesignersBarcode} interface instead.
	 */

	/**
	 * Returns the primary key of this designers barcode.
	 *
	 * @return the primary key of this designers barcode
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this designers barcode.
	 *
	 * @param primaryKey the primary key of this designers barcode
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the designer barcode ID of this designers barcode.
	 *
	 * @return the designer barcode ID of this designers barcode
	 */
	public long getDesignerBarcodeId();

	/**
	 * Sets the designer barcode ID of this designers barcode.
	 *
	 * @param designerBarcodeId the designer barcode ID of this designers barcode
	 */
	public void setDesignerBarcodeId(long designerBarcodeId);

	/**
	 * Returns the barcode ID of this designers barcode.
	 *
	 * @return the barcode ID of this designers barcode
	 */
	public long getBarcodeId();

	/**
	 * Sets the barcode ID of this designers barcode.
	 *
	 * @param barcodeId the barcode ID of this designers barcode
	 */
	public void setBarcodeId(long barcodeId);

	/**
	 * Returns the design ID of this designers barcode.
	 *
	 * @return the design ID of this designers barcode
	 */
	public long getDesignId();

	/**
	 * Sets the design ID of this designers barcode.
	 *
	 * @param designId the design ID of this designers barcode
	 */
	public void setDesignId(long designId);

	/**
	 * Returns the create date of this designers barcode.
	 *
	 * @return the create date of this designers barcode
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this designers barcode.
	 *
	 * @param createDate the create date of this designers barcode
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this designers barcode.
	 *
	 * @return the modified date of this designers barcode
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this designers barcode.
	 *
	 * @param modifiedDate the modified date of this designers barcode
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DesignersBarcode designersBarcode);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DesignersBarcode> toCacheModel();

	@Override
	public DesignersBarcode toEscapedModel();

	@Override
	public DesignersBarcode toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}