/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cloud.tags.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Carts service. Represents a row in the &quot;carts&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cloud.tags.model.impl.CartsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cloud.tags.model.impl.CartsImpl}.
 * </p>
 *
 * @author Mohammed Zaheer
 * @see Carts
 * @see com.cloud.tags.model.impl.CartsImpl
 * @see com.cloud.tags.model.impl.CartsModelImpl
 * @generated
 */
public interface CartsModel extends BaseModel<Carts> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a carts model instance should use the {@link Carts} interface instead.
	 */

	/**
	 * Returns the primary key of this carts.
	 *
	 * @return the primary key of this carts
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this carts.
	 *
	 * @param primaryKey the primary key of this carts
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cart ID of this carts.
	 *
	 * @return the cart ID of this carts
	 */
	public long getCartId();

	/**
	 * Sets the cart ID of this carts.
	 *
	 * @param cartId the cart ID of this carts
	 */
	public void setCartId(long cartId);

	/**
	 * Returns the user ID of this carts.
	 *
	 * @return the user ID of this carts
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this carts.
	 *
	 * @param userId the user ID of this carts
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this carts.
	 *
	 * @return the user uuid of this carts
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this carts.
	 *
	 * @param userUuid the user uuid of this carts
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this carts.
	 *
	 * @return the create date of this carts
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this carts.
	 *
	 * @param createDate the create date of this carts
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this carts.
	 *
	 * @return the modified date of this carts
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this carts.
	 *
	 * @param modifiedDate the modified date of this carts
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the session_id of this carts.
	 *
	 * @return the session_id of this carts
	 */
	@AutoEscape
	public String getSession_id();

	/**
	 * Sets the session_id of this carts.
	 *
	 * @param session_id the session_id of this carts
	 */
	public void setSession_id(String session_id);

	/**
	 * Returns the staff ID of this carts.
	 *
	 * @return the staff ID of this carts
	 */
	@AutoEscape
	public String getStaffId();

	/**
	 * Sets the staff ID of this carts.
	 *
	 * @param staffId the staff ID of this carts
	 */
	public void setStaffId(String staffId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Carts carts);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Carts> toCacheModel();

	@Override
	public Carts toEscapedModel();

	@Override
	public Carts toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}