/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cloud.tags.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StoreDeviceMap service. Represents a row in the &quot;store_device_map&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cloud.tags.model.impl.StoreDeviceMapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cloud.tags.model.impl.StoreDeviceMapImpl}.
 * </p>
 *
 * @author Mohammed Zaheer
 * @see StoreDeviceMap
 * @see com.cloud.tags.model.impl.StoreDeviceMapImpl
 * @see com.cloud.tags.model.impl.StoreDeviceMapModelImpl
 * @generated
 */
public interface StoreDeviceMapModel extends BaseModel<StoreDeviceMap> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a store device map model instance should use the {@link StoreDeviceMap} interface instead.
	 */

	/**
	 * Returns the primary key of this store device map.
	 *
	 * @return the primary key of this store device map
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this store device map.
	 *
	 * @param primaryKey the primary key of this store device map
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this store device map.
	 *
	 * @return the uuid of this store device map
	 */
	public long getUuid();

	/**
	 * Sets the uuid of this store device map.
	 *
	 * @param uuid the uuid of this store device map
	 */
	public void setUuid(long uuid);

	/**
	 * Returns the store name of this store device map.
	 *
	 * @return the store name of this store device map
	 */
	@AutoEscape
	public String getStoreName();

	/**
	 * Sets the store name of this store device map.
	 *
	 * @param storeName the store name of this store device map
	 */
	public void setStoreName(String storeName);

	/**
	 * Returns the device mac address of this store device map.
	 *
	 * @return the device mac address of this store device map
	 */
	@AutoEscape
	public String getDeviceMacAddress();

	/**
	 * Sets the device mac address of this store device map.
	 *
	 * @param deviceMacAddress the device mac address of this store device map
	 */
	public void setDeviceMacAddress(String deviceMacAddress);

	/**
	 * Returns the store ID of this store device map.
	 *
	 * @return the store ID of this store device map
	 */
	public long getStoreId();

	/**
	 * Sets the store ID of this store device map.
	 *
	 * @param storeId the store ID of this store device map
	 */
	public void setStoreId(long storeId);

	/**
	 * Returns the company ID of this store device map.
	 *
	 * @return the company ID of this store device map
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this store device map.
	 *
	 * @param companyId the company ID of this store device map
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this store device map.
	 *
	 * @return the group ID of this store device map
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this store device map.
	 *
	 * @param groupId the group ID of this store device map
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this store device map.
	 *
	 * @return the create date of this store device map
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this store device map.
	 *
	 * @param createDate the create date of this store device map
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StoreDeviceMap storeDeviceMap);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StoreDeviceMap> toCacheModel();

	@Override
	public StoreDeviceMap toEscapedModel();

	@Override
	public StoreDeviceMap toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}