/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cloud.tags.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StoreInformationMap service. Represents a row in the &quot;store_information_map&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cloud.tags.model.impl.StoreInformationMapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cloud.tags.model.impl.StoreInformationMapImpl}.
 * </p>
 *
 * @author Mohammed Zaheer
 * @see StoreInformationMap
 * @see com.cloud.tags.model.impl.StoreInformationMapImpl
 * @see com.cloud.tags.model.impl.StoreInformationMapModelImpl
 * @generated
 */
public interface StoreInformationMapModel extends BaseModel<StoreInformationMap> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a store information map model instance should use the {@link StoreInformationMap} interface instead.
	 */

	/**
	 * Returns the primary key of this store information map.
	 *
	 * @return the primary key of this store information map
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this store information map.
	 *
	 * @param primaryKey the primary key of this store information map
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this store information map.
	 *
	 * @return the uuid of this store information map
	 */
	public long getUuid();

	/**
	 * Sets the uuid of this store information map.
	 *
	 * @param uuid the uuid of this store information map
	 */
	public void setUuid(long uuid);

	/**
	 * Returns the name of this store information map.
	 *
	 * @return the name of this store information map
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this store information map.
	 *
	 * @param Name the name of this store information map
	 */
	public void setName(String Name);

	/**
	 * Returns the address of this store information map.
	 *
	 * @return the address of this store information map
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this store information map.
	 *
	 * @param Address the address of this store information map
	 */
	public void setAddress(String Address);

	/**
	 * Returns the company ID of this store information map.
	 *
	 * @return the company ID of this store information map
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this store information map.
	 *
	 * @param companyId the company ID of this store information map
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this store information map.
	 *
	 * @return the group ID of this store information map
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this store information map.
	 *
	 * @param groupId the group ID of this store information map
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this store information map.
	 *
	 * @return the create date of this store information map
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this store information map.
	 *
	 * @param createDate the create date of this store information map
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StoreInformationMap storeInformationMap);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StoreInformationMap> toCacheModel();

	@Override
	public StoreInformationMap toEscapedModel();

	@Override
	public StoreInformationMap toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}