/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cloud.tags.model.impl;

import com.cloud.tags.model.Impressions;
import com.cloud.tags.service.ImpressionsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Impressions service. Represents a row in the &quot;Impressions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ImpressionsImpl}.
 * </p>
 *
 * @author Mohammed Zaheer
 * @see ImpressionsImpl
 * @see com.cloud.tags.model.Impressions
 * @generated
 */
public abstract class ImpressionsBaseImpl extends ImpressionsModelImpl
	implements Impressions {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a impressions model instance should use the {@link Impressions} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ImpressionsLocalServiceUtil.addImpressions(this);
		}
		else {
			ImpressionsLocalServiceUtil.updateImpressions(this);
		}
	}
}